### ISSUE TITLE
Release tag missing

### ISSUE THREAD

**Issue by 8ctopus** [tareq1988/wp-php-cs-fixer#2]
Hi Tareq, thank you for making this. I've found an issue that can easily be fixed when I try to install the package:

```
$ composer require --dev tareq1988/wp-php-cs-fixer

  Could not find a version of package tareq1988/wp-php-cs-fixer matching your minimum-stability (stable). Require it with an explic
  it version constraint allowing its desired stability.
```

To fix it, you will need to create a first release, so we don't install from dev-master branch which requires to drop the stability requirement.

```
git tag 1.0.0;
git push --tags;
```

At the moment, I've updated my minimum stability like this:

```json
    "minimum-stability": "dev",
    "prefer-stable": true,
```

**Comment by tareq1988** [comment]
Yeah, sorry for that. Made a release at last, so it should be okay from now.

**Comment by 8ctopus** [comment]
Great!
