### ISSUE TITLE
Php cs fixer missing

### ISSUE THREAD

**Issue by 8ctopus** [tareq1988/wp-php-cs-fixer#3]
I would also want to suggest to require php-cs-fixer in composer json so it does not need to be required.

Here's what I have in my composer json at the moment:

```json
....
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require-dev": {
        "tareq1988/wp-php-cs-fixer": "dev-master",
        "friendsofphp/php-cs-fixer": "^3.14"
    }
```

**Comment by tareq1988** [comment]
php-cs-fixer could be installed globally on your computer, hence not required at the repository level.
